In [1]:
import numpy as np
import pandas as pd
import os

In [3]:
from sklearn.feature_extraction.text import CountVectorizer

In [4]:
text = ['the quick brown fox jumped over the lazy dog.']

In [5]:
vectorizer = CountVectorizer()

In [6]:
vectorizer.fit(text)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [7]:
vectorizer.vocabulary_

{'brown': 0,
 'dog': 1,
 'fox': 2,
 'jumped': 3,
 'lazy': 4,
 'over': 5,
 'quick': 6,
 'the': 7}

In [8]:
vector = vectorizer.transform(text)
vector

<1x8 sparse matrix of type '<class 'numpy.int64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [9]:
print(vector.shape)
print(type(vector))

(1, 8)
<class 'scipy.sparse.csr.csr_matrix'>


In [10]:
vector.toarray()

array([[1, 1, 1, 1, 1, 1, 1, 2]])

In [11]:
text2 = ['the kitty']
vector = vectorizer.transform(text2)
print(vector.toarray())

[[0 0 0 0 0 0 0 1]]


In [12]:
vectorizer.get_feature_names()

['brown', 'dog', 'fox', 'jumped', 'lazy', 'over', 'quick', 'the']

In [13]:
df = pd.DataFrame(vector.toarray(),columns=vectorizer.get_feature_names())
df

brown  dog  fox  jumped  lazy  over  quick  the
0      0    0    0       0     0     0      0    1

In [18]:
text1 = ['The quick brown fox jumped over the lazy dog.', 'The dog', 'The fox']

In [16]:
vectorizer1 = CountVectorizer(stop_words='english')
vectorizer1

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words='english',
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [19]:
vector1 = vectorizer1.fit_transform(text1)

In [20]:
print(vector1)

  (0, 5)	1
  (0, 0)	1
  (0, 2)	1
  (0, 3)	1
  (0, 4)	1
  (0, 1)	1
  (1, 1)	1
  (2, 2)	1


In [21]:
vector1.todense()

matrix([[1, 1, 1, 1, 1, 1],
        [0, 1, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0]])

In [22]:
df1 = pd.DataFrame(vector1.toarray(),columns=vectorizer1.get_feature_names())
df1

brown  dog  fox  jumped  lazy  quick
0      1    1    1       1     1      1
1      0    1    0       0     0      0
2      0    0    1       0     0      0

In [27]:
data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data/movies_metadata1.csv')
data.head()

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


adult  ... vote_count
0  False  ...     5415.0
1  False  ...     2413.0
2  False  ...       92.0
3  False  ...       34.0
4  False  ...      173.0

[5 rows x 24 columns]

In [28]:
overview = data['overview']
overview.head()

0    Led by Woody, Andy's toys live happily in his ...
1    When siblings Judy and Peter discover an encha...
2    A family wedding reignites the ancient feud be...
3    Cheated on, mistreated and stepped on, the wom...
4    Just when George Banks has recovered from his ...
Name: overview, dtype: object

In [29]:
vectorizer2 = CountVectorizer(stop_words='english')
vectorizer2

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words='english',
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [30]:
overview.isnull().any()

True

In [32]:
overview.shape

(45466,)

In [33]:
from sklearn.impute import SimpleImputer

In [34]:
imputer = SimpleImputer(missing_values=np.nan,strategy='constant',fill_value='')

In [35]:
overview1 = imputer.fit_transform(np.array(overview.values).reshape(-1,1))
overview1

array([["Led by Woody, Andy's toys live happily in his room until Andy's birthday brings Buzz Lightyear onto the scene. Afraid of losing his place in Andy's heart, Woody plots against Buzz. But when circumstances separate Buzz and Woody from their owner, the duo eventually learns to put aside their differences."],
       ["When siblings Judy and Peter discover an enchanted board game that opens the door to a magical world, they unwittingly invite Alan -- an adult who's been trapped inside the game for 26 years -- into their living room. Alan's only hope for freedom is to finish the game, which proves risky as all three find themselves running from giant rhinoceroses, evil monkeys and other terrifying creatures."],
       ["A family wedding reignites the ancient feud between next-door neighbors and fishing buddies John and Max. Meanwhile, a sultry Italian divorcée opens a restaurant at the local bait shop, alarming the locals who worry she'll scare the fish away. But she's less interest

In [36]:
overview1.shape

(45466, 1)

In [38]:
pd.isnull(overview1).any()

False

In [39]:
overview1 = overview1[:,0]
overview1.shape

(45466,)

In [40]:
vector2=vectorizer2.fit_transform(overview1)
vector2

<45466x75827 sparse matrix of type '<class 'numpy.int64'>'
	with 1210882 stored elements in Compressed Sparse Row format>

In [41]:
len(vectorizer2.vocabulary_.keys())

75827