In [1]:
import numpy as np
import pandas as pd
import os

In [3]:
df = pd.read_csv('play_golf.csv', delimiter = ';')
df.head()

outlook  temp humidity  windy play
0     rainy   hot     high  False   no
1     rainy   hot     high   True   no
2  overcast   hot     high  False  yes
3     sunny  mild     high  False  yes
4     sunny  cool   normal  False  yes

In [4]:
df_X = df.loc[:,'outlook' : 'windy']
df_X

outlook  temp humidity  windy
0      rainy   hot     high  False
1      rainy   hot     high   True
2   overcast   hot     high  False
3      sunny  mild     high  False
4      sunny  cool   normal  False
5      sunny  cool   normal   True
6      sunny  cool   normal   True
7      rainy  mild     high  False
8      rainy  cool   normal  False
9      sunny  mild   normal  False
10     rainy  mild   normal   True
11  overcast  mild     high   True
12  overcast   hot   normal  False
13     sunny  mild     high   True

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df_X1 = pd.DataFrame()
for i in df_X.columns:
  df_X1[i]=le.fit_transform(df_X[i])
df_X1

outlook  temp  humidity  windy
0         1     1         0      0
1         1     1         0      1
2         0     1         0      0
3         2     2         0      0
4         2     0         1      0
5         2     0         1      1
6         2     0         1      1
7         1     2         0      0
8         1     0         1      0
9         2     2         1      0
10        1     2         1      1
11        0     2         0      1
12        0     1         1      0
13        2     2         0      1

In [6]:
from sklearn.preprocessing import OneHotEncoder
onehot_encoder = OneHotEncoder(sparse=False)

In [7]:
data = ['cold','cold','warm','cold','hot','hot','warm','cold','warm','hot']
values = np.array(data)
values

array(['cold', 'cold', 'warm', 'cold', 'hot', 'hot', 'warm', 'cold',
       'warm', 'hot'], dtype='<U4')

In [11]:
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
integer_encoded

array([0, 0, 2, 0, 1, 1, 2, 0, 2, 1])

In [12]:
integer_encoded = integer_encoded.reshape(len(integer_encoded),1)
integer_encoded.shape

(10, 1)

In [13]:
onehot_encoder = OneHotEncoder(sparse=False)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
onehot_encoded

array([[1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])

In [16]:
inverted = label_encoder.inverse_transform([np.argmax(onehot_encoded[0,:])])
inverted

array(['cold'], dtype='<U4')

In [19]:
inverted = []
for i in range(onehot_encoded.shape[0]):
  inverted.append(label_encoder.inverse_transform([np.argmax(onehot_encoded[i,:])]))
inverted

[array(['cold'], dtype='<U4'),
 array(['cold'], dtype='<U4'),
 array(['warm'], dtype='<U4'),
 array(['cold'], dtype='<U4'),
 array(['hot'], dtype='<U4'),
 array(['hot'], dtype='<U4'),
 array(['warm'], dtype='<U4'),
 array(['cold'], dtype='<U4'),
 array(['warm'], dtype='<U4'),
 array(['hot'], dtype='<U4')]

In [22]:
inverted = []
for i in range(onehot_encoded.shape[0]):
  inverted.append(label_encoder.inverse_transform([np.argmax(onehot_encoded[i,:])])[0])
inverted

['cold', 'cold', 'warm', 'cold', 'hot', 'hot', 'warm', 'cold', 'warm', 'hot']

In [23]:
values_np = np.array(inverted)
values_np

array(['cold', 'cold', 'warm', 'cold', 'hot', 'hot', 'warm', 'cold',
       'warm', 'hot'], dtype='<U4')

In [29]:
arr_outlook = np.array(df_X1['outlook'])
arr_outlook = arr_outlook.reshape(len(arr_outlook),1)
arr_outlook

array([[1],
       [1],
       [0],
       [2],
       [2],
       [2],
       [2],
       [1],
       [1],
       [2],
       [1],
       [0],
       [0],
       [2]])

In [38]:
arr_temp = np.array(df_X1['temp'])
arr_temp = arr_temp.reshape(len(arr_temp),1)

In [37]:
arr_humidity = np.array(df_X1['humidity'])
arr_humidity = arr_humidity.reshape(len(arr_humidity),1)


In [36]:
arr_windy = np.array(df_X1['windy'])
arr_windy = arr_windy.reshape(len(arr_windy),1)

In [31]:
onehot_enc_outlook = onehot_encoder.fit_transform(arr_outlook)
onehot_enc_outlook

array([[0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])

In [39]:
onehot_enc_temp = onehot_encoder.fit_transform(arr_temp)
onehot_enc_humidity = onehot_encoder.fit_transform(arr_humidity)
onehot_enc_windy = onehot_encoder.fit_transform(arr_windy)

In [41]:
df_X_encoded = df_X.copy()

In [43]:
df_X_encoded['outlook'] = onehot_enc_outlook
df_X_encoded['temp'] = onehot_enc_temp
df_X_encoded['humidity'] = onehot_enc_humidity
df_X_encoded['windy'] = onehot_enc_windy
df_X_encoded

outlook  temp  humidity  windy
0       0.0   0.0       1.0    1.0
1       0.0   0.0       1.0    0.0
2       1.0   0.0       1.0    1.0
3       0.0   0.0       1.0    1.0
4       0.0   1.0       0.0    1.0
5       0.0   1.0       0.0    0.0
6       0.0   1.0       0.0    0.0
7       0.0   0.0       1.0    1.0
8       0.0   1.0       0.0    1.0
9       0.0   0.0       0.0    1.0
10      0.0   0.0       0.0    0.0
11      1.0   0.0       1.0    0.0
12      1.0   0.0       0.0    1.0
13      0.0   0.0       1.0    0.0